### ISSUE TITLE
a bug in the XALL tool?

### ISSUE THREAD

**Issue by ArgosSoft** [zeffii/mesh_tiny_cad#56] opened 2017-02-13 19:26 UTC
Hi,

First of all thank you for all of these convenient tools :)
I'm mainly using XALL, and sometime it does random things, with the same setup:

I did a python script that build circles and a square, I select all, and I just apply XALL in edit mode:
(the script is a loop on bpy.ops.mesh.primitive_circle_add)

with this setup:
<img width="200" alt="capture d ecran 2017-02-13 a 20 03 37" src="https://cloud.githubusercontent.com/assets/25752092/22898424/8f3601e6-f227-11e6-980d-0a2528fdff9e.png">
(all is (x, y, 0.0) )

sometime I got this (sounds good, and when I check it, everything looks linked as expected):
<img width="200" alt="capture d ecran 2017-02-13 a 20 05 42" src="https://cloud.githubusercontent.com/assets/25752092/22898504/d47ed52a-f227-11e6-849f-583379feccf2.png">
Python output:
```
>>>bpy.ops.tinycad.intersectall()
unselected {515, 4, 5, 6, 7, 8, 9, 10, 11, 518, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 530, 28, 29, 30, 31, 32, 33, 34, 35, 545, 632, 38, 39, 40, 41, 43, 44, 557, 46, 558, 48, 49, 50, 559, 560, 53, 54, 55, 561, 57, 562, 59, 60, 564, 62, 63, 64, 65, 66, 570, 581, 71, 72, 74, 76, 588, 78, 589, 80, 590, 82, 591, 592, 85, 593, 87, 526, 89, 594, 91, 527, 93, 597, 95, 96, 528, 601, 602, 603, 610, 102, 103, 529, 105, 613, 107, 619, 109, 620, 621, 531, 113, 622, 115, 116, 532, 118, 623, 624, 625, 122, 533, 124, 628, 126, 534, 128, 129, 130, 634, 535, 636, 134, 135, 642, 536, 139, 537, 147, 148, 160, 161, 164, 165, 166, 167, 169, 172, 180, 187, 190, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 209, 214, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 635, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 633, 563, 274, 277, 565, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 567, 568, 569, 306, 308, 309, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 332, 333, 334, 335, 336, 337, 340, 341, 342, 343, 344, 345, 346, 347, 349, 350, 351, 352, 353, 354, 355, 357, 358, 359, 361, 363, 364, 366, 367, 368, 369, 371, 374, 375, 376, 377, 379, 380, 382, 384, 385, 386, 389, 391, 626, 393, 395, 397, 399, 400, 402, 407, 408, 410, 412, 414, 416, 566, 418, 627, 420, 422, 426, 428, 430, 432, 433, 595, 435, 438, 439, 596, 441, 443, 445, 449, 598, 451, 452, 599, 600, 460, 464, 465, 629, 467, 469, 470, 471, 631, 483, 484, 491, 630, 494, 496, 497, 498, 499, 500, 501, 502, 503, 505, 508}, non intersecting edges
Info: Removed 852 vertices
{'FINISHED'}
```

and sometime, with the same setup, I got this:
<img width="200" alt="capture d ecran 2017-02-13 a 20 06 32" src="https://cloud.githubusercontent.com/assets/25752092/22898530/f19131f8-f227-11e6-889f-353703332a1e.png"> <img width="243" alt="capture d ecran 2017-02-13 a 20 18 02" src="https://cloud.githubusercontent.com/assets/25752092/22899009/98a387ec-f229-11e6-8708-0ecbc08e18b1.png">
Python output:
```
>>> bpy.ops.tinycad.intersectall()
unselected {515, 4, 5, 6, 7, 8, 9, 10, 11, 518, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 530, 28, 29, 30, 31, 32, 33, 34, 35, 545, 632, 38, 39, 40, 41, 43, 44, 557, 46, 558, 48, 49, 50, 559, 560, 53, 54, 55, 561, 57, 562, 59, 60, 564, 62, 63, 64, 65, 66, 570, 581, 71, 72, 74, 76, 588, 78, 589, 80, 590, 82, 591, 592, 85, 593, 87, 526, 89, 594, 91, 527, 93, 597, 95, 96, 528, 601, 602, 603, 610, 102, 103, 529, 105, 613, 107, 619, 109, 620, 621, 531, 113, 622, 115, 116, 532, 118, 623, 624, 625, 122, 533, 124, 628, 126, 534, 128, 129, 130, 634, 535, 636, 134, 135, 642, 536, 139, 537, 147, 148, 160, 161, 164, 165, 166, 167, 169, 172, 180, 187, 190, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 209, 214, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 635, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 633, 563, 274, 277, 565, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 567, 568, 569, 306, 308, 309, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 332, 333, 334, 335, 336, 337, 340, 341, 342, 343, 344, 345, 346, 347, 349, 350, 351, 352, 353, 354, 355, 357, 358, 359, 361, 363, 364, 366, 367, 368, 369, 371, 374, 375, 376, 377, 379, 380, 382, 384, 385, 386, 389, 391, 626, 393, 395, 397, 399, 400, 402, 407, 408, 410, 412, 414, 416, 566, 418, 627, 420, 422, 426, 428, 430, 432, 433, 595, 435, 438, 439, 596, 441, 443, 445, 449, 598, 451, 452, 599, 600, 460, 464, 465, 629, 467, 469, 470, 471, 631, 483, 484, 491, 630, 494, 496, 497, 498, 499, 500, 501, 502, 503, 505, 508}, non intersecting edges
Info: Removed 948 vertices
{'FINISHED'}
```

Additional information:
tinyCAD Version 1.3.0
Blender 2.78a (OSX)

Any idea? Maybe I'm not using your tool correctly?

Thank you again!

**Comment by zeffii** [comment] 2017-02-13 19:28
yep. sometimes you need to switch in and out of edit mode before running the XALL operator.

**Comment by zeffii** [comment] 2017-02-13 19:34
if you are a little adventurous you can try adding the following lines 
```python
        bpy.ops.object.mode_set(mode='OBJECT')
        bpy.ops.object.mode_set(mode='EDIT')
```
into the top of the execute function in https://github.com/zeffii/mesh_tiny_cad/blob/master/XALL.py#L163-L181

```python
   def execute(self, context):

        bpy.ops.object.mode_set(mode='OBJECT')
        bpy.ops.object.mode_set(mode='EDIT')

        # must force edge selection mode here
        bpy.context.tool_settings.mesh_select_mode = (False, True, False)

        obj = context.active_object
        if obj.mode == "EDIT":
            bm = bmesh.from_edit_mesh(obj.data)

            selected_edges = [edge for edge in bm.edges if edge.select]
            edge_indices = [i.index for i in selected_edges]

            d = get_intersection_dictionary(bm, edge_indices)

            unselect_nonintersecting(bm, d.keys(), edge_indices)
            update_mesh(obj, d)
        else:
            print('must be in edit mode')

        return {'FINISHED'}
```

**Comment by zeffii** [comment] 2017-02-13 19:39
@ArgosSoft   if you do that.. let me know how it goes. If it tames the Mesh, then i'm tempted to add those lines to the version distributed with Blender too.

**Comment by ArgosSoft** [comment] 2017-02-13 20:46
I added the 2 lines into the top of the execute function (and restarted Blender), and before my intersectall() call ... same thing, sometime it works, sometime it does random things, in a unpredictable way :/
<img height="200" alt="capture d ecran 2017-02-13 a 21 44 51" src="https://cloud.githubusercontent.com/assets/25752092/22902544/b8a71d7c-f235-11e6-83b4-49f6989d2727.png"> <img height="200" alt="capture d ecran 2017-02-13 a 21 44 24" src="https://cloud.githubusercontent.com/assets/25752092/22902539/b4102916-f235-11e6-8d47-54dc89c90450.png">

**Comment by zeffii** [comment] 2017-02-14 04:09
Ok , thanks for checking. I recently wrote replacement code for that function for sverchok. Maybe you would provide a simple script I can test your scenario with. I hope to get around to this in 2 days

**Comment by ArgosSoft** [comment] 2017-02-14 12:20
Here is a minimal example of my script:
```python
import bpy

# new object
me = bpy.data.meshes.new('myMesh') 
ob = bpy.data.objects.new('myObject', me)
bpy.context.scene.objects.link(ob)

# selection and EDIT mode
bpy.context.scene.objects.active = ob
ob.select = True
bpy.ops.object.mode_set(mode='EDIT')

# circles part 1
center = (0, 0.5, 0)
step = 0.2
radiusMax = 2
r = 0
while r < radiusMax:
    r = r + step
    bpy.ops.mesh.primitive_circle_add(vertices=32, radius=r, location=center)
    
# circles part 2
center = (0, -0.5, 0)
step = 0.2
radiusMax = 2
r = 0
while r < radiusMax:
    r = r + step
    bpy.ops.mesh.primitive_circle_add(vertices=32, radius=r, location=center)

# edit mode switch
bpy.ops.object.mode_set(mode='OBJECT')
bpy.ops.object.mode_set(mode='EDIT')

# XALL call
bpy.ops.mesh.select_all(action='SELECT')
bpy.ops.tinycad.intersectall()
```

With this script sometime I got this (as expected):
<img height="200" alt="capture d ecran 2017-02-14 a 13 12 49" src="https://cloud.githubusercontent.com/assets/25752092/22928568/74d2e608-f2b7-11e6-84e2-753b9be62625.png">

And sometime this:
<img height="200" alt="capture d ecran 2017-02-14 a 13 12 20" src="https://cloud.githubusercontent.com/assets/25752092/22928566/72011d78-f2b7-11e6-8f8b-bb90449791d0.png">

**Comment by zeffii** [comment] 2017-02-14 15:16
@ArgosSoft excellent! i'm eager to fix this btw, it has bugged me for the longest time - I get so few reports about XALL 

my own experiments in the past have shown that the problem isn't really any specific type of geometry, but rather an index shuffling upon initialization..  First i hope my replacement code will solve this (it is the least invasive edit i'd like to try first), then ..well.. i don't really want to think about that yet.

**Comment by zeffii** [comment] 2017-02-14 15:19
for good measure i'll add a feature that let's you specify remove doubles / and doubles distance - the call would become: 

```python
bpy.ops.tinycad.intersectall()
# or
bpy.ops.tinycad.intersectall(rm_doubles=True, distance=0.0001)
```

**Comment by zeffii** [comment] 2017-02-14 15:29
one thing I might not be able to fix is this scenario, that you present: namely - a lot of vertices share common space

![image](https://cloud.githubusercontent.com/assets/619340/22935381/be1ec8a2-f2d2-11e6-8de9-aa5e19dd1074.png)

You might have more luck by removing doubles first, then doing intersectall.

**Comment by zeffii** [comment] 2017-02-14 15:32
(but in this case that doesn't seem to matter)

This might come down to a problem of limited precision in 32-bit float numbers and my rather crude algorithm that assumes very little shared vertex geometry ( like.. no verts located on the same 3d locations)

**Comment by zeffii** [comment] 2017-02-14 15:43
A proof would be if you rotated each circle a little to slightly offset the problem. Let's try 0 phase in sverchok 

Before intersect all : 

![image](https://cloud.githubusercontent.com/assets/619340/22935949/579b98a6-f2d4-11e6-8ec3-d830a4e67c04.png)

and after intersect all (almost same code, but as a node.. using the newer code)

![image](https://cloud.githubusercontent.com/assets/619340/22936061/a5ace6f8-f2d4-11e6-9c59-a17e2fad9c9d.png)

thus..I'm inclined to _still_ think this is fixed with the change in code.

**Comment by zeffii** [comment] 2017-02-14 15:45
but won't dance on its grave just yet.

**Comment by zeffii** [comment] 2017-02-14 16:19
no ETA btw.. it's not a small change.

**Comment by ArgosSoft** [comment] 2017-02-14 17:43
With a small change in my script: `center = (0, 0.52, 0)` And `center = (0, -0.52, 0)`

No more vert are located on the same location (`bpy.ops.mesh.remove_doubles` return `Info: Removed 0 vertices {'FINISHED'}`)

And I still got the same issue, maybe a floating precision problem as you said?

**Comment by zeffii** [comment] 2017-02-14 19:53
No, I think i've already been able to confirm that "co-location" wasn't the problem i reasoned it might be, and with that finding i'm not considering floating point the real problem either.

A small rewrite will happen as soon as i have some free time (and silence around me)

**Comment by zeffii** [comment] 2017-02-14 20:22
![image](https://cloud.githubusercontent.com/assets/619340/22947480/74bd33b4-f2fb-11e6-88a3-5452a0c79109.png)

I have a different branch to test this in, if you are comfortable with such things:  
https://github.com/zeffii/mesh_tiny_cad/pull/57

**Comment by zeffii** [comment] 2017-02-14 20:42
can't say with much certainty that it's fixed in the Branch 'XALL_F4bm`  , but it's looking promising

![image](https://cloud.githubusercontent.com/assets/619340/22948361/7abf1360-f2fe-11e6-8b32-71071b1e5977.png)

**Comment by ArgosSoft** [comment] 2017-02-14 21:16
I'm trying [#57](https://github.com/zeffii/mesh_tiny_cad/pull/57), it seems to be better, after few execution the result looks good :)

**Comment by zeffii** [comment] 2017-02-14 21:31
that's all I can do for now, without going deeper.   

- as you can see on the screenshot, there is some extra geometry generated where two edges run almost parallel.

**Comment by zeffii** [comment] 2017-02-14 21:35
this seems to be caused by the code that does the initial "deselection of non-intersecting edges"

**Comment by zeffii** [comment] 2017-02-17 08:35
i've pushed this to master and to blender/addons repo.

closing unless @ArgosSoft reopens.

**Closed by zeffii** 2017-02-17 08:35 UTC
Labels: bug
