### ISSUE TITLE
Unable to weld intersecting edges

### ISSUE THREAD

**Issue by carlotm** [zeffii/mesh_tiny_cad#78] opened 2021-05-16 05:42 UTC
The `VTX | Auto` operation results in this error:

`Non Planar Edges, no clean intersection point`

I am pretty sure the adges are planar, here is an example blend file to reproduce:
https://tilde.club/~carloratm/downloads/tinycad_bug_report.blend

I am using Blender 2.92.0
[system-info.txt](https://github.com/zeffii/mesh_tiny_cad/files/6488742/system-info.txt)

**Comment by zeffii** [comment] 2021-05-16 16:16
yep. i can confirm, this looks very much to be down to the precision being lost when the geometry is larger in scale.

i've only modelled using Blender's default environment scale.

**Comment by zeffii** [comment] 2021-05-16 16:17
i'll have a look at making this adaptive, or atleast adjustable.

**Comment by zeffii** [comment] 2021-05-16 17:04
btw, try adding a Cube to that scene you sent me.  1m cubed is so small in that scene. you'll have to zoom way in.  Then try tinyCAD at that scale.

**Comment by carlotm** [comment] 2021-05-17 05:32
I changed the global unit scale to 0.001 just to be sure I will always be in "mm space", but that is not a hard requirement.

I confirm setting the Unit Scale back to 1.0 makes TinyCAD work perfectly.

To me, this bug can be closed.
If you want to work on making TinyCAD adaptive to unit scales, I can help you with testing :)

Thank you,
Carlo

**Comment by zeffii** [comment] 2021-05-17 17:49
thanks,  i'll close this for now,   but might eventually add some form of adaptive "epsilon/tolerance" setting.  I've never needed to change the default scaling, since writing the first lines of code for this in 2009.

**Closed** 2021-05-17 17:49 UTC
